language: python
fast_finish: true

python:
  - 3.6

os:
  - linux

group: travis_latest

git:
  depth: 3


install: pip -q install -e .[tests]

script: pytest -v 

after_success: 
  - coverage run tests/test_all.py
  - coveralls
